[book]
authors = ["yoshiaki"]
language = "en"
multilingual = false
src = "src"
title = "組込みシステムIII"

# codeblock にファイル名を表示 see https://crates.io/crates/mdbook-codename
[preprocessor.codename] 

# pagetoc https://crates.io/crates/mdbook_pagetoc/0.2.0
[preprocessor.pagetoc]

[output.html]
mathjax-support = true
# 日本語検索 see https://blog.bridgey.dev/2023/06/14/search-japanese-on-mdbook/
additional-js   = ["assets/fzf.umd.js", "assets/elasticlunr.js", "theme/pagetoc.js"]
additional-css  = ["theme/pagetoc.css"]

[output.html.code.hidelines]
sv = "!!!"